### PR TITLE
Add custom keywords, and Chinese translation

### PR DESCRIPTION
**Pull request by youthlin**
**test**

- `npm run test` passed.

**what changed and why**

- README.md: add a link to README_zh.md
- dev/App.vue: add a property name `lang`, so I can use `<Demo lang='zh_CN'/>` in docs/zh/demo.md
- dev/components/DemoAlert.vue: a demo for custom global properties
- dev/components/DemoDateFormat.vue: add zh locale
- dev/i18n.ts: new file, used by dev/main.ts and docs/.vuepress/client.ts
- docs/.vuepress/config.ts: enable [Internationalization](https://vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config)
- docs/configuration.md: update default config, add `globalProperties`
- docs/extraction.md: update default config, add `jsExtractorOpts`
- docs/zh/*: add zh translation
- gettext.config.js: update extract config, add locale, add `jsExtractorOpts` to extract the custom keywords
- scripts/config.ts: add `jsExtractorOpts` to GettextConfig
- scripts/extract.ts: add extracors to support custom keywords
- scripts/gettext_extract.ts: add comment for `msginit`
- scripts/utils.ts: pass env to child process, so `msginit` can access the `GETTEXTCLDRDIR` variable
- src/index.ts: add support for custom global properties
- src/typeDefs.ts: update type defs of `GetTextOptions`, `GettextConfig`

### CODE REVIEW

**Comment by youthlin** [comment]
fix https://github.com/jshmrtn/vue3-gettext/issues/20

**Comment by youthlin** [comment]
> Hi @youthlin, thanks for your PR! I will need some time to review this, you may need some patience.
> 
> I have to admit I'm a bit weary about adding Chinese docs, mainly because I have no way to maintain them myself. I will probably merge them, but please add a warning disclaimer to make it clear that the chinese docs are not actively maintained/that they may diverge from the package version.

Thanks for your reply!
I have added a translation notes on docs, please help review.
I would watch this repo, and can synchronize the Chinese translation regularly.

**Comment by youthlin** [comment]
@lzurbriggen Hi, can those code to be merged? What should I do more to help

**Comment by jeremyzahner** [comment]
> @lzurbriggen Hi, can those code to be merged? What should I do more to help

Hi @youthlin!

@lzurbriggen is back in tomorrow. I guess he will get back to you as soon as he can.

**Review by jeremyzahner — APPROVED** [review]

**Comment by lzurbriggen** [comment]
@youthlin I don't really have the time to review this in detail, but it looks good in general. I'll merge this and create a pre-release. I may make some changes before I create a final release.

**Pull request merged**
